import type { SeriesCharacter } from "./character-fetcher";

/**
 * AI-synthesized Comprehensive Character Encyclopedia (Priority 2 Fallback).
 * Contains rich, canon-accurate character dossiers, deep cultivation/martial lore,
 * narrative impact, continuous story roles, quotes, and relationship networks.
 */
export const AI_SERIES_CHARACTERS: Record<string, SeriesCharacter[]> = {
  "i-am-the-fated-villain": [
    {
      id: "fated-gu-changge",
      seriesSlug: "i-am-the-fated-villain",
      slug: "gu-changge",
      name: "Gu Changge",
      nativeName: "顾长歌",
      aliases: [
        "Young Master Gu",
        "God-Child",
        "Successor of Demonic Arts",
        "Young Supreme",
        "Reincarnation of Human Ancestor",
        "Lord of Heavenly Court",
      ],
      role: "MAIN",
      roleTitle: "Protagonist • Demonic Arts Inheritor",
      imageUrl: "https://static.wikia.nocookie.net/i-am-the-fated-villan/images/d/df/Gu_changge.png/revision/latest?cb=20220126223414",
      description:
        "Gu Changge is the ruthless, calculative transmigrator who awoke as the Young Master of the Ancient Immortal Gu Family and the True Successor of the Heavenly Dao Immortal Palace. Armed with the Fated Villain System, he ruthlessly schemes against the 'Sons of Luck' (protagonists chosen by destiny), systematically plundering their luck points, divine bones, and heavenly techniques to forge his own supreme path toward boundless dao supremacy.",
      personality:
        "Calm, charismatic, deeply manipulative, and profoundly ruthless. He wears a facade of a righteous, untouchable Young Supreme in the public eye while operating as the merciless inheritor of the forbidden Demonic Arts from the shadows. Never underestimates his foes and treats the entire Upper and Lower Realms as his chessboard.",
      background:
        "Originally a modern youth who transmigrated into the body of the Ancient Immortal Gu Family's heir. In his youth, the original host excavated the Dao Bone of his younger cousin, Gu Xian'er, creating a lifelong feud. Upon awakening with the Villain System, Changge resolved to rectify past vulnerabilities, turning all enemies into stepping stones for his ascension.",
      storySignificance:
        "The absolute driving force of the entire series. Gu Changge's relentless schematics dismantle the clichéd tropes of traditional cultivation protagonists (ring grandpas, reincarnated god kings, dragon sons of god), harvesting their providence to fuel his cosmic supremacy.",
      bioData: {
        gender: "Male",
        age: "21 (Initial Awakening) / Ascendant",
        status: "Active • Supreme Sovereign",
        roleType: "Protagonist",
        combatClass: "Demonic Arts Sovereign / Sword Immortal",
        cultivationRealm: "Supreme Realm → True Immortal → Immortal King",
        affiliation: "Ancient Immortal Gu Family • Heavenly Dao Immortal Palace • Divine Kingdom",
        physique: "Innate Demon Heart & Bone of Transcendence • Immortal Body",
        innateTalent: "Heavenly Demonic Swallowing Art • Void Dao Mastery",
        weapons: ["Eight Desolations Demon Halberd", "Immortal Slaying Gourd", "Void Mirror"],
        abilities: [
          "Swallowing Demon Heavenly Art",
          "Void Immortal Step",
          "Nine Transformations of the Demonic Body",
          "Myriad Dao Annihilation",
          "Dao Bone Resonance",
        ],
        firstAppearance: "Chapter 1",
        identity: "Heir of Ancient Immortal Gu Family & Successor of Demonic Arts",
      },
      relationships: [
        {
          name: "Gu Xian'er",
          slug: "gu-xianer",
          relationType: "Cousin & Former Victim",
          description:
            "His younger cousin whose Dao Bone he excavated in childhood. Changge secretly protects her growth while manipulating her hatred into unstoppable strength.",
          isSpoiler: true,
        },
        {
          name: "Yue Mingkong",
          slug: "yue-mingkong",
          relationType: "Fiancée & Reborn Empress",
          description:
            "Reborn Empress who remembers Changge murdering her in her previous life. Their dynamic evolves into a supreme power couple bound by intellect and ambition.",
          isSpoiler: true,
        },
        {
          name: "Su Qingge",
          slug: "su-qingge",
          relationType: "Holy Maiden & Trusted Follower",
          description:
            "Holy Maiden of Taixuan Holy Land. Changge recognized her hidden supreme soul and elevated her into one of his most reliable confidantes.",
          isSpoiler: false,
        },
        {
          name: "Yin Mei",
          slug: "yin-mei",
          relationType: "Loyal Enforcer",
          description:
            "Nine-Tailed Fox Holy Maiden who serves as Changge's indispensable shadow operative, managing merchant guilds and framing Sons of Luck.",
          isSpoiler: false,
        },
        {
          name: "Ye Chen",
          slug: "ye-chen",
          relationType: "Fated Enemy (Son of Luck)",
          description:
            "The initial Destiny's Child whose providence and ring mentor were systematically plundered by Gu Changge.",
          isSpoiler: false,
        },
      ],
      quotes: [
        "In this world, there are no villains or heroes—only those who sit atop the heavens and those beneath their feet.",
        "A Son of Luck is just a ripe harvest waiting to be reaped.",
      ],
      trivia: [
        "He has plundered over a dozen different destiny halos throughout the Upper and Lower Realms.",
        "His Demon Heart allows him to consume supreme bloodlines without soul backlash.",
      ],
      sourceUrl: "https://i-am-the-fated-villain.fandom.com/wiki/Gu_Changge",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "fated-gu-xianer",
      seriesSlug: "i-am-the-fated-villain",
      slug: "gu-xianer",
      name: "Gu Xian'er",
      nativeName: "顾仙儿",
      aliases: ["Little Fairy", "Destiny's Heroine", "Princess of the Gu Clan", "Goddess of Peach Blossom"],
      role: "MAIN",
      roleTitle: "Female Lead • Reborn Dao Bone Prodigy",
      imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b282811-Q8n3jP26kGwh.jpg",
      description:
        "Gu Xian'er is Gu Changge's younger cousin and the true Destiny's Heroine of the series. After having her innate Dao Bone dug out by Gu Changge in childhood, she was sent to the desolate outer region. Under the tutelage of several enigmatic master hermit masters and a mystical Peach Tree spirit, she miraculously regenerated a supreme Nirvana Dao Bone and swore vengeance against Gu Changge.",
      personality:
        "Tsundere, prideful, stubbornly resilient, and secretly deeply affectionate. Beneath her prickly exterior and constant vows to 'beat Gu Changge half to death', she gradually realizes the immense unspoken sacrifices Changge made to forge her into an invincible immortal.",
      background:
        "Born as the beloved daughter of the Gu clan branch. The loss of her Dao Bone almost destroyed her foundation, but her unbroken will allowed her to achieve Nirvana rebirth. Supported by the ancient Peach Tree entity, she entered the Upper Realm to challenge the younger generation.",
      storySignificance:
        "The emotional core of the novel's clan politics. Her interactions with Gu Changge provide comic relief, dramatic tension, and deep emotional resonance as the mystery behind the Dao Bone excavation unravels.",
      bioData: {
        gender: "Female",
        age: "18",
        status: "Active • Daoist Prodigy",
        roleType: "Main Cast / Heroine",
        combatClass: "Nirvana Sword Cultivator",
        cultivationRealm: "God King Realm → Sacred Realm",
        affiliation: "Ancient Immortal Gu Family • Peach Blossom Village",
        physique: "Nirvana Rebirth Dao Bone • Pure Immortal Spirit Body",
        weapons: ["Immortal Peach Branch", "Feathered Immortal Sword"],
        abilities: ["Nirvana Rebirth Scripture", "Peach Petal Sword Domain", "Nine Heavens Feather Step"],
        firstAppearance: "Chapter 12",
        identity: "Branch Princess of Ancient Immortal Gu Family",
      },
      relationships: [
        {
          name: "Gu Changge",
          slug: "gu-changge",
          relationType: "Cousin & Fated Nemesis/Protector",
          description:
            "Her hated cousin who stole her bone, yet constantly orchestrates golden opportunities for her cultivation in secret.",
          isSpoiler: true,
        },
        {
          name: "Yue Mingkong",
          slug: "yue-mingkong",
          relationType: "Sisterly Alliance",
          description:
            "Formed an early sisterly bond with Yue Mingkong, both venting their grievances about Gu Changge's devious character.",
          isSpoiler: false,
        },
      ],
      quotes: [
        "Gu Changge! One day, I will definitely step on your arrogant face and make you apologize!",
      ],
      trivia: [
        "She loves collecting shiny treasures and spirit stones, exhibiting a cute dragon-like hoarding habit.",
      ],
      sourceUrl: "https://i-am-the-fated-villain.fandom.com/wiki/Gu_Xian%27er",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "fated-yue-mingkong",
      seriesSlug: "i-am-the-fated-villain",
      slug: "yue-mingkong",
      name: "Yue Mingkong",
      nativeName: "月明空",
      aliases: ["Empress of Immortal Yue Dynasty", "Crown Princess", "Moon Empress"],
      role: "MAIN",
      roleTitle: "Female Lead • Reborn Sovereign Empress",
      imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b282813-w46o5Qk6z57C.jpg",
      description:
        "Yue Mingkong is the Crown Princess and supreme ruler of the Immortal Yue Dynasty, as well as Gu Changge's fiancée. She was murdered by Gu Changge on their wedding night in her previous life. Reborn into her youth with full memories of the future, she resolves to counter Gu Changge's schemes, only to find that this lifetime's Gu Changge is far more terrifying, unpredictable, and surprisingly tender.",
      personality:
        "Regal, calculating, politically shrewd, and deeply traumatized by her past death. Possesses iron leadership over the Yue Dynasty, matching Gu Changge in intellect and willpower.",
      background:
        "Reborn with future foresight regarding ancient ruins, Son of Luck appearances, and Upper Realm cataclysms. Initially terrified of Changge, she gradually realizes he is a different soul who truly regards her as his sovereign peer.",
      storySignificance:
        "Gu Changge's greatest intellectual equal and romantic partner. Together, they form an invincible duo that plunders the realms and dismantles ancient sects.",
      bioData: {
        gender: "Female",
        age: "21",
        status: "Active • Empress",
        roleType: "Main Cast / Empress",
        combatClass: "Imperial Emperor Arts Cultivator",
        cultivationRealm: "Great Sacred Realm → Quasi-Supreme",
        affiliation: "Immortal Yue Divine Dynasty",
        physique: "Imperial Moon Sacred Body",
        weapons: ["Immortal Moon Imperial Mirror", "Dragon Phoenix Sword"],
        abilities: ["Immortal Yue Sovereign Scripture", "Moonlight Domain", "Future Foresight"],
        firstAppearance: "Chapter 15",
        identity: "Crown Princess & Empress of Immortal Yue Dynasty",
      },
      relationships: [
        {
          name: "Gu Changge",
          slug: "gu-changge",
          relationType: "Fiancé & Former Executioner",
          description:
            "Her murderer in her past life, but her true lifelong sovereign partner and protector in this timeline.",
          isSpoiler: true,
        },
        {
          name: "Gu Xian'er",
          slug: "gu-xianer",
          relationType: "Sisterly Bond",
          description: "Shares a close bond with Xian'er, offering her maternal-like guidance and protection.",
          isSpoiler: false,
        },
      ],
      quotes: [
        "Gu Changge, in this life, I will not let you kill me again... even if I have to tie you to my throne.",
      ],
      trivia: [
        "She originally planned to assassinate Gu Changge before his demonic arts matured, but kept hesitating due to lingering love.",
      ],
      sourceUrl: "https://i-am-the-fated-villain.fandom.com/wiki/Yue_Mingkong",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "fated-su-qingge",
      seriesSlug: "i-am-the-fated-villain",
      slug: "su-qingge",
      name: "Su Qingge",
      nativeName: "苏清歌",
      aliases: ["Holy Maiden of Taixuan", "Dual-Soul Maiden"],
      role: "SUPPORTING",
      roleTitle: "Heroine • Dual-Soul Sacred Maiden",
      imageUrl: "https://static.wikia.nocookie.net/i-am-the-fated-villan/images/6/6a/Su_Quingge.png/revision/latest?cb=20220126230543",
      description:
        "Su Qingge is the revered Holy Maiden of the Taixuan Holy Land in the Lower Realm. Blessed with peerless beauty and intelligence, she harbored an ancient supreme second soul. When Ye Chen attempted to use her as a traditional protagonist trophy, Gu Changge appeared and offered her real protection and autonomy, turning her into his first loyal confidante.",
      personality:
        "Gentle, discerning, perceptive, and unfailingly loyal to Gu Changge. Possesses sharp emotional intelligence, immediately discerning Changge's dark genius and willingly serving as his pawn.",
      background:
        "Born in the Lower Realm with an enigmatic Upper Realm lineage. When her Holy Land was threatened, she chose to serve Gu Changge, eventually awakening her latent Demonic Soul.",
      storySignificance:
        "The first heroine Gu Changge detached from a destiny protagonist. Her loyalty remains unwavering even after learning pieces of Changge's dark identity.",
      bioData: {
        gender: "Female",
        age: "19",
        status: "Active",
        roleType: "Core Supporting",
        combatClass: "Dual-Soul Spirit Mistress",
        cultivationRealm: "Void Spirit Realm → True God Realm",
        affiliation: "Taixuan Holy Land • Upper Realm Ancient Family",
        physique: "Pure Yin Spirit Body • Hidden Ancient Demonic Soul",
        abilities: ["Taixuan Holy Method", "Soul Awakening", "Yin Spirit Frost Domain"],
        firstAppearance: "Chapter 1",
        identity: "Holy Maiden of Taixuan Holy Land",
      },
      relationships: [
        {
          name: "Gu Changge",
          slug: "gu-changge",
          relationType: "Master & Benefactor",
          description: "Devoted follower who trusts Gu Changge completely above all sects.",
          isSpoiler: false,
        },
        {
          name: "Ye Chen",
          slug: "ye-chen",
          relationType: "Former Fellow Disciple",
          description: "Rejected Ye Chen's entitlement and severed all ties with him.",
          isSpoiler: false,
        },
      ],
      quotes: [
        "Young Master Gu's wisdom is beyond the mortal realm. I will never regret standing by his side.",
      ],
      trivia: ["Her hidden second soul belonged to a supreme empress from the ancient devil realm."],
      sourceUrl: "https://i-am-the-fated-villain.fandom.com/wiki/Su_Qingge",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "fated-lin-qiuhan",
      seriesSlug: "i-am-the-fated-villain",
      slug: "lin-qiuhan",
      name: "Lin Qiuhan",
      nativeName: "林秋寒",
      aliases: ["Young Mistress Lin", "Alchemy Genius"],
      role: "SUPPORTING",
      roleTitle: "Supporting • Pill Dao Prodigy",
      imageUrl: "https://static.wikia.nocookie.net/i-am-the-fated-villan/images/d/d2/Lin_Quihan02.jpg/revision/latest?cb=20220317174917",
      description:
        "Lin Qiuhan is the eldest young mistress of the prestigious Lin Clan in the Middle Realm. Possessing an innate disposition for alchemy that dwarfs ancient masters, she caught Gu Changge's interest. Changge introduced her to ancient pill scriptures, transforming her into a grandmaster alchemist who manages medicinal supplies for the Gu clan.",
      personality:
        "Diligent, earnest, kindhearted, and passionately devoted to the Dao of Alchemy. Deeply grateful to Gu Changge for believing in her talent.",
      background:
        "The pride of the Lin family. Her cousin Lin Tian was overtaken by a reincarnated God King, whom Changge helped her expose and neutralize.",
      storySignificance:
        "Manages crucial logistical and medicinal infrastructure for Gu Changge's faction, serving as his primary alchemist in the lower and middle realms.",
      bioData: {
        gender: "Female",
        age: "20",
        status: "Active",
        roleType: "Supporting Alchemist",
        combatClass: "Grandmaster Alchemist",
        cultivationRealm: "Transformed God Realm",
        affiliation: "Lin Clan • Ancient Immortal Gu Family",
        physique: "Innate Medicine Spirit Physique",
        abilities: ["Nine Sun Pill Fire", "Ancient Pill Dao Scripture", "Herb Spirit Purification"],
        firstAppearance: "Chapter 5",
        identity: "Heir of the Lin Clan & Chief Alchemist",
      },
      relationships: [
        {
          name: "Gu Changge",
          slug: "gu-changge",
          relationType: "Lord & Mentor",
          description: "Respects Changge as her greatest benefactor and cultivation guide.",
          isSpoiler: false,
        },
        {
          name: "Lin Tian",
          slug: "lin-tian",
          relationType: "Cousin",
          description: "Her cousin whose possession by a reincarnated soul was uncovered by Changge.",
          isSpoiler: true,
        },
      ],
      quotes: ["With Young Master Gu's guidance, my furnace will never fail."],
      trivia: ["Can refine flawless heaven-grade pills with a 99% success rate."],
      sourceUrl: "https://i-am-the-fated-villain.fandom.com/wiki/Lin_Quihan",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "fated-yin-mei",
      seriesSlug: "i-am-the-fated-villain",
      slug: "yin-mei",
      name: "Yin Mei",
      nativeName: "尹湄",
      aliases: ["Fox Fairy", "Holy Maiden of Nine Tails", "Mistress of Wan Dao Commerce"],
      role: "SUPPORTING",
      roleTitle: "Supporting • Shadow Operative & Merchant Mistress",
      imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b282814-F9t70v3hP1aE.jpg",
      description:
        "Yin Mei is the peerless Holy Maiden of the Nine-Tailed Heavenly Fox Clan and the covert ruler of the Wan Dao Merchant Alliance. Placed under Gu Changge's service early on, she served as his primary double agent, seamlessly framing rival Sons of Luck (such as Ye Ling) for the forbidden Demonic Arts crimes while ensuring Changge remained spotless.",
      personality:
        "Seductive, razor-sharp, cunning, and fiercely loyal. She takes immense pleasure in high-stakes espionage and considers her servitude to Changge her proudest accomplishment.",
      background:
        "Heir to the Nine-Tailed Heavenly Fox bloodline. Realized early that Gu Changge was the only sovereign destined to conquer the Upper Realm and pledged eternal fealty.",
      storySignificance:
        "Essential to Gu Changge's framing of Ye Ling and his takeover of the Wan Dao Merchant Alliance, securing vast economic hegemony across the cosmos.",
      bioData: {
        gender: "Female",
        age: "22",
        status: "Active",
        roleType: "Core Shadow Operative",
        combatClass: "Illusion & Fox Fire Sorceress",
        cultivationRealm: "God King Realm → Sacred Realm",
        affiliation: "Nine-Tailed Fox Clan • Wan Dao Merchant Alliance",
        physique: "Nine-Tailed Heavenly Fox Bloodline",
        weapons: ["Nine Tails Soul Ribbon", "Heavenly Fox Bell"],
        abilities: ["Heavenly Fox Charm", "Soul Puppet Thread", "Nine Fox Illusions"],
        firstAppearance: "Chapter 30",
        identity: "Holy Maiden of Nine-Tailed Fox Clan",
      },
      relationships: [
        {
          name: "Gu Changge",
          slug: "gu-changge",
          relationType: "Master & Secret Sovereign",
          description: "Her absolute lord whose orders she carries out with fanatical precision.",
          isSpoiler: false,
        },
      ],
      quotes: ["A single rumor orchestrated properly is more lethal than an emperor's sword."],
      trivia: ["Possesses 9 pure white tails that only Gu Changge has been permitted to touch."],
      sourceUrl: "https://i-am-the-fated-villain.fandom.com/wiki/Yin_Mei",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "fated-yan-ji",
      seriesSlug: "i-am-the-fated-villain",
      slug: "yan-ji",
      name: "Yan Ji",
      nativeName: "严姬",
      aliases: ["Empress of Crimson Flame", "Great Sacred Flame Spirit"],
      role: "SUPPORTING",
      roleTitle: "Supporting • Ancient Flame Sovereign & Mentor",
      imageUrl: "https://static.wikia.nocookie.net/i-am-the-fated-villan/images/e/ed/Yanji02png.png/revision/latest?cb=20220317183628",
      description:
        "Yan Ji was originally the ancient Great Sacred remnant soul dwelling inside Ye Chen's mystical ring, acting as his miraculous cultivation mentor. When Ye Chen proved ungrateful, arrogant, and suspicious of her guidance, Gu Changge intervened. Changge forged a supreme Sacred Body for her, prompting her to abandon Ye Chen and become Changge's loyal martial guardian.",
      personality:
        "Mature, dignified, wise, and deeply grateful. Holds immense ancient knowledge of Upper Realm history and forgotten Dao scriptures.",
      background:
        "A former Great Sacred realm powerhouse who lost her physical body during an ancient war. Bound to a spirit ring until rescued and restored by Gu Changge.",
      storySignificance:
        "Demonstrates Gu Changge's signature strategy of stealing the 'Ring Grandpa/Mentor' from Destiny's Children, entirely stripping Ye Chen of his cultivation foundation.",
      bioData: {
        gender: "Female",
        age: "Thousands of Years (Spirit)",
        status: "Active • Restored Sacred Body",
        roleType: "Guardian & Mentor",
        combatClass: "Sacred Flame Mage",
        cultivationRealm: "Great Sacred Realm → Quasi-Supreme",
        affiliation: "Ancient Immortal Gu Family",
        physique: "Nine Heavens Crimson Flame Physique",
        abilities: ["Red Lotus Karmic Fire", "Great Sacred Flame Domain", "Sacred Soul Forging"],
        firstAppearance: "Chapter 3",
        identity: "Ancient Great Sacred Spirit & Royal Guardian",
      },
      relationships: [
        {
          name: "Gu Changge",
          slug: "gu-changge",
          relationType: "Lord & Body Reconstructor",
          description: "Bound by deep gratitude to Changge for restoring her flesh and cultivation.",
          isSpoiler: false,
        },
        {
          name: "Ye Chen",
          slug: "ye-chen",
          relationType: "Former Ungrateful Disciple",
          description: "Severed all master-disciple ties after Ye Chen blamed her for his shortcomings.",
          isSpoiler: false,
        },
      ],
      quotes: ["Ye Chen, your heart is corrupted by ego. My debt to you was paid long ago."],
      trivia: ["Her Red Lotus Karmic Flame can incinerate the souls of False Gods within seconds."],
      sourceUrl: "https://i-am-the-fated-villain.fandom.com/wiki/Yan_Ji",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "fated-ye-chen",
      seriesSlug: "i-am-the-fated-villain",
      slug: "ye-chen",
      name: "Ye Chen",
      nativeName: "叶尘",
      aliases: ["Son of Luck", "Disciple of Taixuan", "Ring Bearer"],
      role: "ANTAGONIST",
      roleTitle: "Destined Rival • Son of Luck (Early)",
      imageUrl: "https://static.wikia.nocookie.net/i-am-the-fated-villan/images/3/3b/Ye_chen.png/revision/latest?cb=20220317172726",
      description:
        "Ye Chen was a standard archetypal xianxia protagonist: born into a humble clan, carrying an ancient ring containing a powerful female mentor spirit (Yan Ji), and blessed with overwhelming luck. However, when he crossed paths with Gu Changge, his plot armor shattered. Changge methodically stripped him of his reputation, his holy maiden companion, his master, and finally his destiny points.",
      personality:
        "Hotheaded, arrogant, entitled, and convinced the universe revolves around him. Unable to accept that anyone could surpass his destiny.",
      background:
        "Outcast of the Taixuan Holy Land. Believed he was the chosen dragon among men until Gu Changge revealed the vast gulf between mortal luck and true sovereign authority.",
      storySignificance:
        "The introductory Destiny's Child who teaches readers the fundamental mechanics of Gu Changge's Villain System and fortune harvesting.",
      bioData: {
        gender: "Male",
        age: "18",
        status: "Deceased / Harvested",
        roleType: "Early Rival",
        combatClass: "Ring-Assisted Sword Cultivator",
        cultivationRealm: "True Sea Realm → Soul Palace",
        affiliation: "Taixuan Holy Land (Former)",
        abilities: ["Nine Heavens Burning Sun Art", "Ring Spirit Borrowing", "Fortune Surge"],
        firstAppearance: "Chapter 1",
        identity: "Former Taixuan Disciple & Destiny's Child",
      },
      relationships: [
        {
          name: "Gu Changge",
          slug: "gu-changge",
          relationType: "Fated Nemesis",
          description: "His nightmare who stripped every lucky break and divine artifact he possessed.",
          isSpoiler: false,
        },
        {
          name: "Yan Ji",
          slug: "yan-ji",
          relationType: "Former Ring Master",
          description: "Blamed and alienated his master, driving her to defect to Changge.",
          isSpoiler: false,
        },
      ],
      quotes: ["Thirty years east of the river, thirty years west! Gu Changge, do not bully the young and poor!"],
      trivia: ["His death yielded Gu Changge his first massive batch of 2,000 Fate Points and a Heavenly Treasure Chest."],
      sourceUrl: "https://i-am-the-fated-villain.fandom.com/wiki/Ye_Chen",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "fated-ye-liuli",
      seriesSlug: "i-am-the-fated-villain",
      slug: "ye-liuli",
      name: "Ye Liuli",
      nativeName: "叶琉璃",
      aliases: ["Little Princess of the Ye Clan", "Sword Deity Scion"],
      role: "SUPPORTING",
      roleTitle: "Supporting • Immortal Ye Clan Princess",
      imageUrl: "https://static.wikia.nocookie.net/i-am-the-fated-villan/images/2/25/Yeliuli01.png/revision/latest?cb=20220317184520",
      description:
        "Ye Liuli is the proud princess of the Ancient Immortal Ye Clan in the Upper Realm. Possessing the ancestral Sword Deity Bloodline, she initially descended to the Lower Realm to investigate Ye Chen's lineage. Gu Changge easily outmaneuvered her escort, subdued her haughtiness, and converted her into a valuable diplomatic link to the Ye Clan.",
      personality:
        "Pampered, proud, sword-obsessed, but inherently noble and compliant once thoroughly outmatched.",
      background:
        "Daughter of the Ancient Immortal Ye Clan. Carries an ancestral sword bone that resonates with celestial sword intents.",
      storySignificance:
        "Provided Gu Changge with early diplomatic leverage over the Ancient Immortal Ye Clan in the Upper Realm.",
      bioData: {
        gender: "Female",
        age: "18",
        status: "Active",
        roleType: "Upper Realm Scion",
        combatClass: "Sword Deity Cultivator",
        cultivationRealm: "God King Realm",
        affiliation: "Ancient Immortal Ye Clan",
        physique: "Sword Deity Ancestral Bloodline",
        weapons: ["Snow River Ancient Sword"],
        abilities: ["Ye Clan Sword Intent", "Seven Star Piercing Sword"],
        firstAppearance: "Chapter 10",
        identity: "Princess of Ancient Immortal Ye Clan",
      },
      relationships: [
        {
          name: "Gu Changge",
          slug: "gu-changge",
          relationType: "Sovereign Senior",
          description: "Initially fearful of Changge, now holds profound awe for his martial dominance.",
          isSpoiler: false,
        },
      ],
      quotes: ["The sword has no second chance. In front of Gu Changge, my blade trembled for the first time."],
      trivia: ["Her ancestor was a peerless Sword Immortal who cleaved a galaxy in half."],
      sourceUrl: "https://i-am-the-fated-villain.fandom.com/wiki/Ye_Liuli",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "fated-lin-tian",
      seriesSlug: "i-am-the-fated-villain",
      slug: "lin-tian",
      name: "Lin Tian",
      nativeName: "林天",
      aliases: ["Reincarnated God King", "Ancient Canghai God King"],
      role: "ANTAGONIST",
      roleTitle: "Destined Rival • Reincarnated God King",
      imageUrl: "https://static.wikia.nocookie.net/i-am-the-fated-villan/images/8/81/Lin_tian.png/revision/latest?cb=20220317175950",
      description:
        "Lin Tian was a mediocre disciple of the Lin Clan whose body was possessed by the reincarnated Canghai God King. Armed with thousands of years of God King combat memories and pill formulas, he believed he could conquer the Middle Realm. However, Gu Changge instantly saw through his reincarnation disguise and dismantled him completely.",
      personality:
        "Condescending, proud, harboring an obsolete god-king complex that failed against modern villain cunning.",
      background:
        "Former God King of the Divine Realm who perished and reincarnated into Lin Qiuhan's clan cousin.",
      storySignificance:
        "Represents the 'Reincarnated Ancient God King' trope, completely dismantled by Gu Changge to claim the Lin Clan's loyalty.",
      bioData: {
        gender: "Male",
        age: "Thousands of Years (Soul)",
        status: "Deceased / Harvested",
        roleType: "Mid-Realm Antagonist",
        combatClass: "God King Soul Reincarnator",
        cultivationRealm: "God King Soul / Mortal Vessel",
        affiliation: "Lin Clan (Host) • Canghai Divine Palace",
        abilities: ["Canghai God King Fist", "Divine Soul Suppression"],
        firstAppearance: "Chapter 8",
        identity: "Reincarnated Canghai God King",
      },
      relationships: [
        {
          name: "Gu Changge",
          slug: "gu-changge",
          relationType: "Executioner",
          description: "Unmasked and eradicated by Gu Changge before his God King powers could re-mature.",
          isSpoiler: false,
        },
        {
          name: "Lin Qiuhan",
          slug: "lin-qiuhan",
          relationType: "Clan Cousin",
          description: "Attempted to use Qiuhan as a cauldron, prompting her to side with Changge.",
          isSpoiler: true,
        },
      ],
      quotes: ["I am the Canghai God King! How could an Upper Realm brat see through my divine soul?!"],
      trivia: ["Gu Changge extracted his God King Soul Core to forge pills for his subordinates."],
      sourceUrl: "https://i-am-the-fated-villain.fandom.com/wiki/Lin_Tian",
      updatedAt: new Date().toISOString(),
    },
  ],
  "revenge-of-the-iron-blooded-sword-hound": [
    {
      id: "hound-vikir",
      seriesSlug: "revenge-of-the-iron-blooded-sword-hound",
      slug: "vikir-van-baskerville",
      name: "Vikir Van Baskerville",
      nativeName: "비키르 반 바스커빌",
      aliases: ["Night Hound", "Iron-Blooded Hunting Dog", "Decaback Swordmaster", "Ghost of Underworld"],
      role: "MAIN",
      roleTitle: "Protagonist • Reborn Swordmaster",
      imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b302194-PzS9y9cK6QkR.jpg",
      description:
        "Vikir is the reborn hunting dog of the Iron-Blooded Baskerville Clan. In his first life, he committed countless bloody assassinations for his father, Hugo Le Baskerville, only to be beheaded on false treason charges. Reborn back to his infancy with full memories of the demonic invasion and hidden ancestral sword techniques, Vikir vows to dismantle the corrupt Baskerville bloodline from within.",
      personality:
        "Cold, hyper-vigilant, pragmatic, yet deeply honorable to those who show true loyalty. He views combat with mathematical precision and refuses to let emotion cloud his blade.",
      background:
        "An illegitimate son of Hugo Le Baskerville. Survived the deadly Cradle of Swords trial in infancy and grew to become the clan's deadliest weapon.",
      storySignificance:
        "The central protagonist whose strategic rebirth rewrites the fate of the entire continent against the impending demonic cataclysm.",
      bioData: {
        gender: "Male",
        age: "18 (Physical) / 40+ (Battle Veteran)",
        status: "Active • Graduated Hunter",
        roleType: "Protagonist",
        combatClass: "Iron-Blooded Swordmaster & Assassin",
        cultivationRealm: "Swordmaster (Graduated) → 6-Sword Master",
        affiliation: "House of Baskerville • Balak Tribe • Colosseum",
        physique: "Iron-Blooded Hound Constitution • Balak Wolf Blessing",
        weapons: ["Baskerville 7-Tooth Demonic Sword", "Balak Poison Bow"],
        abilities: ["Baskerville 7-Tooth Sword Style", "Night Hound Stealth", "Balak Wolf Senses", "Aura Blade Resonance"],
        firstAppearance: "Chapter 1",
        identity: "Illegitimate Son of Hugo & Secret Night Hound",
      },
      relationships: [
        {
          name: "Hugo Le Baskerville",
          slug: "hugo-le-baskerville",
          relationType: "Ruthless Father & Target",
          description: "His tyrannical father who executed him in his previous life. Vikir now forces him to respect his undeniable power.",
          isSpoiler: true,
        },
        {
          name: "Aiyen",
          slug: "aiyen",
          relationType: "Tribal Comrade & Partner",
          description: "Daughter of the Balak Wolf Chieftain who recognized Vikir's martial prowess and fought beside him in the jungle.",
          isSpoiler: false,
        },
        {
          name: "Sinclair",
          slug: "sinclair",
          relationType: "Magic Academy Ally",
          description: "Brilliant Magic Tower scholar who uncovers secret demonic runes with Vikir.",
          isSpoiler: false,
        },
      ],
      quotes: [
        "A hound does not bite for loyalty anymore. It bites to survive.",
        "Father, this time, it is I who will choose when the hound strikes.",
      ],
      trivia: ["Can survive in freezing wilderness for weeks subsisting entirely on raw monster marrow."],
      sourceUrl: "https://revengeoftheironbloodedswordhound.fandom.com/wiki/Vikir",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "hound-hugo",
      seriesSlug: "revenge-of-the-iron-blooded-sword-hound",
      slug: "hugo-le-baskerville",
      name: "Hugo Le Baskerville",
      nativeName: "위고 르 바스커빌",
      aliases: ["Iron-Blooded Patriarch", "7-Sword Swordmaster", "Sovereign of Iron"],
      role: "MAIN",
      roleTitle: "Patriarch • 7-Sword Swordmaster",
      imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b302195-2gD73W5e2R2N.jpg",
      description:
        "Hugo is the undisputed Patriarch of the Iron-Blooded Baskerville Clan and one of the supreme Swordmasters of the continent. Believing solely in the law of the jungle and the purity of iron, he treats his children as hounds to be tested, discarded, or sharpened. Vikir's inexplicable genius gradually shakes his ruthless worldview.",
      personality:
        "Monolithic, unforgiving, strictly meritocratic, and utterly devoid of outward paternal warmth.",
      background:
        "Master of the full 7-Tooth Baskerville Demonic Sword style. Elevated House Baskerville into the continent's most feared military powerhouse.",
      storySignificance:
        "The primary pillar and authority figure of House Baskerville. His approval and eventual shock at Vikir's genius drive early arcs.",
      bioData: {
        gender: "Male",
        age: "52",
        status: "Active • Patriarch",
        roleType: "Main Patriarch",
        combatClass: "7-Tooth Grand Swordmaster",
        cultivationRealm: "7-Sword Master (Supreme Realm)",
        affiliation: "House of Baskerville",
        physique: "Supreme Baskerville Steel Body",
        weapons: ["Ancestral Bloodtooth Greatsword"],
        abilities: ["Full 7-Tooth Demon Sword", "Iron Blood Domain", "Supreme Aura Roar"],
        firstAppearance: "Chapter 1",
        identity: "Patriarch of House Baskerville",
      },
      relationships: [
        {
          name: "Vikir Van Baskerville",
          slug: "vikir-van-baskerville",
          relationType: "Illegitimate Prodigy Son",
          description: "Initially regarded Vikir as expendable, now recognizes him as the clan's greatest martial genius.",
          isSpoiler: false,
        },
      ],
      quotes: ["In Baskerville, a child is either iron or rust. Rust is discarded."],
      trivia: ["His sword aura alone can split castle walls from fifty paces."],
      sourceUrl: "https://revengeoftheironbloodedswordhound.fandom.com/wiki/Hugo",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "hound-aiyen",
      seriesSlug: "revenge-of-the-iron-blooded-sword-hound",
      slug: "aiyen",
      name: "Aiyen",
      nativeName: "아이엔",
      aliases: ["Wolf Princess of Balak", "Master Hunter of the Sea of Trees"],
      role: "SUPPORTING",
      roleTitle: "Core Heroine • Balak Wolf Archer",
      imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b302196-8Pq1R3k8X7yL.jpg",
      description:
        "Aiyen is the fierce, wild daughter of the Balak Tribe chieftain residing in the deadly Sea of Trees jungle. An unmatched hunter who commands giant shadow wolves, she saved Vikir after his fall into the jungle and chose him as her lifelong companion after witnessing his fearless survival instincts.",
      personality:
        "Fierce, uninhibited, deeply loyal, and straightforward in love and battle. Laughs in the face of death.",
      background:
        "The greatest archer in the history of the Balak Tribe. Commands the deadly Red Wolf pack.",
      storySignificance:
        "Provides Vikir with the ancient poison arts and archery techniques that allow him to operate as the elusive Night Hound.",
      bioData: {
        gender: "Female",
        age: "19",
        status: "Active",
        roleType: "Core Supporting / Companion",
        combatClass: "Beast Archer & Jungle Stalker",
        cultivationRealm: "Graduated Jungle Hunter",
        affiliation: "Balak Wolf Tribe",
        physique: "Balak Beast Bloodline",
        weapons: ["Bone Greatbow", "Curare Poison Daggers"],
        abilities: ["Beast Roar Arrow", "Shadow Wolf Summoning", "Absolute Tracking"],
        firstAppearance: "Chapter 22",
        identity: "Heir Princess of Balak Tribe",
      },
      relationships: [
        {
          name: "Vikir Van Baskerville",
          slug: "vikir-van-baskerville",
          relationType: "Tribal Partner & Life Companion",
          description: "Formed an unbreakable bond with Vikir in the Sea of Trees.",
          isSpoiler: false,
        },
      ],
      quotes: ["You fought the Great Ape with just a dagger. You are my hunter now, Vikir."],
      trivia: ["Can hit a flying wasp between the eyes from 300 meters in dense fog."],
      sourceUrl: "https://revengeoftheironbloodedswordhound.fandom.com/wiki/Aiyen",
      updatedAt: new Date().toISOString(),
    },
  ],
};
