export interface MemeSticker {
  id: string;
  name: string;
  category: "hype" | "funny" | "reaction" | "crying" | "cute" | "hype_moments" | "all";
  emoji: string;
  tag: string;
  url: string;
  fallbackGradient?: string;
  alt: string;
}

export const POPULAR_MEME_STICKERS: MemeSticker[] = [
  // ── HYPE & PEAK MOMENTS ─────────────────────────────────────
  {
    id: "peak-fiction",
    name: "Peak Fiction",
    category: "hype",
    emoji: "🗿",
    tag: "PEAK",
    url: "/memes/peak-fiction.gif",
    fallbackGradient: "from-amber-600 to-orange-700",
    alt: "Peak Fiction Gunna Writing Fire GIF",
  },
  {
    id: "absolute-cinema",
    name: "Absolute Cinema",
    category: "hype",
    emoji: "🍿",
    tag: "CINEMA",
    url: "/memes/absolute-cinema.gif",
    fallbackGradient: "from-purple-600 to-indigo-800",
    alt: "Absolute Cinema Scorsese GIF",
  },
  {
    id: "nah-id-win",
    name: "Nah, I'd Win",
    category: "hype",
    emoji: "🔥",
    tag: "GOJO",
    url: "/memes/nah-id-win.gif",
    fallbackGradient: "from-blue-600 to-cyan-600",
    alt: "Nah I'd Win Gojo Satoru Smirk GIF",
  },
  {
    id: "gojo-honored-one",
    name: "The Honored One",
    category: "hype",
    emoji: "✨",
    tag: "HONORED",
    url: "/memes/gojo-honored-one.gif",
    fallbackGradient: "from-sky-500 to-indigo-900",
    alt: "Gojo Satoru Honored One Awakened GIF",
  },
  {
    id: "sukuna-shrine",
    name: "Malevolent Shrine",
    category: "hype",
    emoji: "🏯",
    tag: "SUKUNA",
    url: "/memes/sukuna-shrine.gif",
    fallbackGradient: "from-red-900 to-black",
    alt: "Sukuna Malevolent Shrine Domain GIF",
  },
  {
    id: "luffy-gear-5",
    name: "Gear 5 Joyboy",
    category: "hype",
    emoji: "🥁",
    tag: "GEAR 5",
    url: "/memes/luffy-gear-5.gif",
    fallbackGradient: "from-amber-400 to-yellow-600",
    alt: "Luffy Gear 5 Sun God Nika Laughing GIF",
  },
  {
    id: "zoro-chad",
    name: "Nothing Happened",
    category: "hype",
    emoji: "🗡️",
    tag: "ZORO",
    url: "/memes/zoro-chad.gif",
    fallbackGradient: "from-emerald-800 to-zinc-950",
    alt: "Zoro Nothing Happened Chad GIF",
  },
  {
    id: "pure-aura",
    name: "Pure Aura (+10,000)",
    category: "hype",
    emoji: "⚡",
    tag: "AURA",
    url: "/memes/pure-aura.gif",
    fallbackGradient: "from-yellow-500 to-amber-600",
    alt: "Super Saiyan Pure Aura GIF",
  },
  {
    id: "aizen-plan",
    name: "According to Plan",
    category: "hype",
    emoji: "👓",
    tag: "AIZEN",
    url: "/memes/aizen-plan.gif",
    fallbackGradient: "from-violet-900 to-slate-950",
    alt: "Aizen All According to Plan Bleach GIF",
  },
  {
    id: "eren-freedom",
    name: "T A T A K A E",
    category: "hype",
    emoji: "🕊️",
    tag: "FREEDOM",
    url: "/memes/eren-freedom.gif",
    fallbackGradient: "from-stone-800 to-amber-950",
    alt: "Eren Yeager Tatakae Freedom Attack on Titan GIF",
  },
  {
    id: "gigachad",
    name: "Gigachad",
    category: "hype",
    emoji: "👑",
    tag: "CHAD",
    url: "/memes/gigachad.gif",
    fallbackGradient: "from-zinc-700 to-zinc-900",
    alt: "Gigachad Meme GIF",
  },
  {
    id: "let-him-cook",
    name: "Let Him Cook",
    category: "hype",
    emoji: "🍳",
    tag: "COOKING",
    url: "/memes/let-him-cook.gif",
    fallbackGradient: "from-emerald-600 to-teal-800",
    alt: "Let Him Cook GIF",
  },
  {
    id: "domain-expansion",
    name: "Domain Expansion",
    category: "hype",
    emoji: "🤞",
    tag: "JJK",
    url: "/memes/domain-expansion.gif",
    fallbackGradient: "from-violet-600 to-purple-900",
    alt: "Domain Expansion Gojo Hand Sign GIF",
  },
  {
    id: "my-goat",
    name: "My GOAT",
    category: "hype",
    emoji: "🐐",
    tag: "GOAT",
    url: "/memes/my-goat.gif",
    fallbackGradient: "from-rose-600 to-pink-800",
    alt: "My GOAT Tribute GIF",
  },

  // ── FUNNY & TROLL ───────────────────────────────────────────
  {
    id: "anya-heh",
    name: "Anya Heh",
    category: "funny",
    emoji: "😏",
    tag: "SMUG",
    url: "/memes/anya-heh.gif",
    fallbackGradient: "from-pink-500 to-rose-600",
    alt: "Anya Smug Heh Face GIF",
  },
  {
    id: "dio-walk",
    name: "Kono DIO Da!",
    category: "funny",
    emoji: "🧛",
    tag: "DIO",
    url: "/memes/dio-walk.gif",
    fallbackGradient: "from-yellow-600 to-purple-900",
    alt: "Dio Brando Walking Approaching Meme GIF",
  },
  {
    id: "light-laugh",
    name: "Light Evil Laugh",
    category: "funny",
    emoji: "😈",
    tag: "EVIL",
    url: "/memes/light-laugh.gif",
    fallbackGradient: "from-red-800 to-black",
    alt: "Light Yagami Death Note Laugh GIF",
  },
  {
    id: "kaguya-cute",
    name: "How Cute... 😏",
    category: "funny",
    emoji: "🥀",
    tag: "HOW CUTE",
    url: "/memes/kaguya-cute.gif",
    fallbackGradient: "from-pink-900 to-rose-950",
    alt: "Kaguya Shinomiya O Kawaii Koto GIF",
  },
  {
    id: "gintoki-nose",
    name: "Gintoki Bored",
    category: "funny",
    emoji: "🥱",
    tag: "GINTOKI",
    url: "/memes/gintoki-nose.gif",
    fallbackGradient: "from-slate-700 to-blue-900",
    alt: "Gintoki Picking Nose Gintama GIF",
  },
  {
    id: "yamcha-pose",
    name: "Yamcha In Crater",
    category: "funny",
    emoji: "🕳️",
    tag: "YAMCHA",
    url: "/memes/yamcha-pose.gif",
    fallbackGradient: "from-amber-900 to-stone-900",
    alt: "Yamcha Death Pose In Crater GIF",
  },
  {
    id: "bocchi-melt",
    name: "Bocchi Melting",
    category: "funny",
    emoji: "🫠",
    tag: "BOCCHI",
    url: "/memes/bocchi-melt.gif",
    fallbackGradient: "from-pink-600 to-fuchsia-900",
    alt: "Bocchi The Rock Melting Anxiety GIF",
  },
  {
    id: "fraud-watch",
    name: "Fraud Watch",
    category: "funny",
    emoji: "🤡",
    tag: "FRAUD",
    url: "/memes/fraud-watch.gif",
    fallbackGradient: "from-red-600 to-orange-700",
    alt: "Fraud Watch Clown GIF",
  },
  {
    id: "saitama-ok",
    name: "Saitama OK",
    category: "funny",
    emoji: "🥊",
    tag: "OK",
    url: "/memes/saitama-ok.gif",
    fallbackGradient: "from-yellow-600 to-red-600",
    alt: "Saitama OK Face GIF",
  },
  {
    id: "skull-dead",
    name: "I'm Dead 💀",
    category: "funny",
    emoji: "💀",
    tag: "DEAD",
    url: "/memes/skull-dead.gif",
    fallbackGradient: "from-zinc-800 to-black",
    alt: "Skull Dying of Laughter GIF",
  },
  {
    id: "popcorn-drama",
    name: "Here for Drama",
    category: "funny",
    emoji: "🍿",
    tag: "DRAMA",
    url: "/memes/popcorn-drama.gif",
    fallbackGradient: "from-amber-500 to-yellow-600",
    alt: "Eating Popcorn Drama GIF",
  },
  {
    id: "stonks-up",
    name: "Manga Stocks 📈",
    category: "funny",
    emoji: "📈",
    tag: "STONKS",
    url: "/memes/stonks-up.gif",
    fallbackGradient: "from-emerald-600 to-green-700",
    alt: "Stonks Rising GIF",
  },
  {
    id: "cat-dance",
    name: "Vibing / Happy",
    category: "funny",
    emoji: "💃",
    tag: "VIBE",
    url: "/memes/cat-dance.gif",
    fallbackGradient: "from-pink-600 to-purple-600",
    alt: "Cat Jam Vibing GIF",
  },

  // ── CHAPTER REACTIONS & TWISTS ───────────────────────────────
  {
    id: "makima-gaze",
    name: "Makima Stare",
    category: "reaction",
    emoji: "👁️‍🗨️",
    tag: "MAKIMA",
    url: "/memes/makima-gaze.gif",
    fallbackGradient: "from-rose-900 to-red-950",
    alt: "Makima Hypnotic Stare Chainsaw Man GIF",
  },
  {
    id: "shocked-enel",
    name: "Shocked Face",
    category: "reaction",
    emoji: "😱",
    tag: "SHOCK",
    url: "/memes/shocked-enel.gif",
    fallbackGradient: "from-blue-500 to-indigo-700",
    alt: "Shocked Face Meme GIF",
  },
  {
    id: "plot-twist-mindblown",
    name: "Plot Twist!",
    category: "reaction",
    emoji: "🤯",
    tag: "TWIST",
    url: "/memes/plot-twist-mindblown.gif",
    fallbackGradient: "from-indigo-600 to-violet-800",
    alt: "Mind Blown Galaxy Reaction GIF",
  },
  {
    id: "he-just-like-me",
    name: "Literally Me Fr",
    category: "reaction",
    emoji: "🕶️",
    tag: "LITERAL ME",
    url: "/memes/he-just-like-me.gif",
    fallbackGradient: "from-slate-700 to-slate-900",
    alt: "Literally Me Fr Ryan Gosling GIF",
  },
  {
    id: "sipping-tea",
    name: "Sipping Tea ☕",
    category: "reaction",
    emoji: "☕",
    tag: "CHILL",
    url: "/memes/sipping-tea.gif",
    fallbackGradient: "from-amber-700 to-stone-800",
    alt: "Sipping Tea Kermit GIF",
  },
  {
    id: "sus-glance",
    name: "Wait... Sus 🤨",
    category: "reaction",
    emoji: "🤨",
    tag: "SUS",
    url: "/memes/sus-glance.gif",
    fallbackGradient: "from-orange-600 to-stone-900",
    alt: "The Rock Eyebrow Raise Sus GIF",
  },
  {
    id: "bro-ran-away",
    name: "NIGERUNDAYO!",
    category: "reaction",
    emoji: "🏃",
    tag: "RUN",
    url: "/memes/bro-ran-away.gif",
    fallbackGradient: "from-amber-600 to-red-700",
    alt: "Joseph Joestar Running Away GIF",
  },

  // ── CRYING & EMOTIONAL DAMAGE ───────────────────────────────
  {
    id: "vegeta-rain-sad",
    name: "Vegeta In Rain",
    category: "crying",
    emoji: "🌧️",
    tag: "VEGETA",
    url: "/memes/vegeta-rain-sad.gif",
    fallbackGradient: "from-blue-950 to-slate-900",
    alt: "Vegeta Staring In Rain Sad GIF",
  },
  {
    id: "deku-crying-fountain",
    name: "Deku Waterworks",
    category: "crying",
    emoji: "😭",
    tag: "DEKU",
    url: "/memes/deku-crying-fountain.gif",
    fallbackGradient: "from-emerald-900 to-cyan-950",
    alt: "Deku Crying Water Stream Tears GIF",
  },
  {
    id: "naruto-sad-swing",
    name: "Sad Swing Music",
    category: "crying",
    emoji: "🪵",
    tag: "NARUTO",
    url: "/memes/naruto-sad-swing.gif",
    fallbackGradient: "from-amber-800 to-slate-900",
    alt: "Naruto Sad Swing Flashback Theme GIF",
  },
  {
    id: "cliffhanger-pain",
    name: "Need Next Ch!",
    category: "crying",
    emoji: "😫",
    tag: "NEED NEXT CH",
    url: "/memes/cliffhanger-pain.gif",
    fallbackGradient: "from-blue-700 to-slate-900",
    alt: "Crying In Agony Need Next Chapter GIF",
  },
  {
    id: "emotional-damage",
    name: "Emotional Damage",
    category: "crying",
    emoji: "😭",
    tag: "PAIN",
    url: "/memes/emotional-damage.gif",
    fallbackGradient: "from-rose-700 to-red-900",
    alt: "Emotional Damage Meme GIF",
  },
  {
    id: "aqua-crying",
    name: "Aqua Crying",
    category: "crying",
    emoji: "😭",
    tag: "SOB",
    url: "/memes/aqua-crying.gif",
    fallbackGradient: "from-cyan-600 to-blue-800",
    alt: "Aqua Konosuba Crying GIF",
  },
  {
    id: "guts-pain",
    name: "Guts Theme / Suffering",
    category: "crying",
    emoji: "⚔️",
    tag: "GUTS",
    url: "/memes/guts-pain.gif",
    fallbackGradient: "from-zinc-800 to-neutral-950",
    alt: "Guts Berserk Suffering GIF",
  },
  {
    id: "salute-respect",
    name: "Respect / Salute",
    category: "crying",
    emoji: "🫡",
    tag: "SALUTE",
    url: "/memes/salute-respect.gif",
    fallbackGradient: "from-emerald-700 to-slate-900",
    alt: "Crying Salute Respect GIF",
  },

  // ── CHIBI & WHOLESOME ───────────────────────────────────────
  {
    id: "pochita-cute",
    name: "Pochita Happy",
    category: "cute",
    emoji: "🐶",
    tag: "POCHITA",
    url: "/memes/pochita-cute.gif",
    fallbackGradient: "from-orange-500 to-amber-700",
    alt: "Pochita Chainsaw Man Happy Bark GIF",
  },
  {
    id: "anya-waku-waku",
    name: "Waku Waku ✨",
    category: "cute",
    emoji: "✨",
    tag: "EXCITED",
    url: "/memes/anya-waku-waku.gif",
    fallbackGradient: "from-pink-500 to-purple-600",
    alt: "Anya Waku Waku Excited Sparkle GIF",
  },
  {
    id: "anya-heh-smug",
    name: "Anya Smug (Heh)",
    category: "funny",
    emoji: "😏",
    tag: "ANYA HEH",
    url: "/memes/anya-heh-smug.gif",
    fallbackGradient: "from-pink-600 to-rose-700",
    alt: "Anya Smug Heh Face Spy x Family GIF",
  },
  {
    id: "jinwoo-arise",
    name: "ARISE (Shadow Monarch)",
    category: "hype",
    emoji: "👑",
    tag: "ARISE",
    url: "/memes/jinwoo-arise.gif",
    fallbackGradient: "from-purple-950 to-indigo-950",
    alt: "Sung Jinwoo Arise Solo Leveling GIF",
  },
  {
    id: "jinwoo-eyes",
    name: "Blue Eyes Aura",
    category: "hype",
    emoji: "⚡",
    tag: "GLOW EYES",
    url: "/memes/jinwoo-eyes.gif",
    fallbackGradient: "from-blue-600 to-cyan-800",
    alt: "Sung Jinwoo Glowing Eyes Solo Leveling GIF",
  },
  {
    id: "lloyd-evil-smile",
    name: "Lloyd Scheming Face",
    category: "funny",
    emoji: "😈",
    tag: "LLOYD",
    url: "/memes/lloyd-evil-smile.gif",
    fallbackGradient: "from-emerald-700 to-teal-900",
    alt: "Lloyd Frontera Evil Grin Greatest Estate Developer GIF",
  },
  {
    id: "frieren-smug",
    name: "Smug Frieren",
    category: "funny",
    emoji: " smug ",
    tag: "FRIEREN",
    url: "/memes/frieren-smug.gif",
    fallbackGradient: "from-slate-600 to-indigo-800",
    alt: "Frieren Smug Expression GIF",
  },
  {
    id: "fern-pout",
    name: "Fern Pout",
    category: "cute",
    emoji: "😤",
    tag: "POUT",
    url: "/memes/fern-pout.gif",
    fallbackGradient: "from-purple-600 to-pink-700",
    alt: "Fern Pouting Face Frieren GIF",
  },
  {
    id: "stand-proud-sukuna",
    name: "Stand Proud, You're Strong",
    category: "hype",
    emoji: "🔥",
    tag: "STAND PROUD",
    url: "/memes/stand-proud-sukuna.gif",
    fallbackGradient: "from-red-950 to-amber-950",
    alt: "Sukuna Stand Proud JJK GIF",
  },
  {
    id: "mahoraga-summon",
    name: "With This Treasure I Summon",
    category: "reaction",
    emoji: "☸️",
    tag: "MAHORAGA",
    url: "/memes/mahoraga-summon.gif",
    fallbackGradient: "from-neutral-900 to-stone-950",
    alt: "Megumi Summoning Mahoraga Wheel GIF",
  },
  {
    id: "eren-tatakae",
    name: "Tatakae (Fight)",
    category: "hype",
    emoji: "🦅",
    tag: "TATAKAE",
    url: "/memes/eren-tatakae.gif",
    fallbackGradient: "from-amber-900 to-stone-900",
    alt: "Eren Yeager Tatakae Mirror Scene GIF",
  },
  {
    id: "madara-reality",
    name: "Wake Up To Reality",
    category: "reaction",
    emoji: "👁️",
    tag: "MADARA",
    url: "/memes/madara-reality.gif",
    fallbackGradient: "from-red-900 to-slate-950",
    alt: "Madara Uchiha Wake Up To Reality GIF",
  },
  {
    id: "toji-nah",
    name: "Toji Speed Flex",
    category: "hype",
    emoji: "💪",
    tag: "TOJI",
    url: "/memes/toji-nah.gif",
    fallbackGradient: "from-zinc-800 to-black",
    alt: "Toji Fushiguro Speed Blitz GIF",
  },
  {
    id: "gigachad-phonk",
    name: "Average Manhwa Reader",
    category: "hype",
    emoji: "🗿",
    tag: "GIGACHAD",
    url: "/memes/gigachad-phonk.gif",
    fallbackGradient: "from-zinc-700 to-zinc-950",
    alt: "GigaChad Chad Jawline GIF",
  },
  {
    id: "cat-typing-fast",
    name: "Scanning Next Ch",
    category: "funny",
    emoji: "⌨️",
    tag: "TYPING",
    url: "/memes/cat-typing-fast.gif",
    fallbackGradient: "from-cyan-700 to-blue-900",
    alt: "Cat Typing Keyboard Super Fast GIF",
  },
  {
    id: "pop-cat-loop",
    name: "Pop Cat",
    category: "funny",
    emoji: "🐱",
    tag: "POPCAT",
    url: "/memes/pop-cat-loop.gif",
    fallbackGradient: "from-amber-400 to-orange-600",
    alt: "Pop Cat Opening Mouth GIF",
  },
  {
    id: "smug-knife-cat",
    name: "Smug Cat",
    category: "funny",
    emoji: "😼",
    tag: "SMUG CAT",
    url: "/memes/smug-knife-cat.gif",
    fallbackGradient: "from-violet-700 to-indigo-900",
    alt: "Smug Cat With Knife GIF",
  },
  {
    id: "dicaprio-cheers",
    name: "DiCaprio Cheers",
    category: "reaction",
    emoji: "🥂",
    tag: "CHEERS",
    url: "/memes/dicaprio-cheers.gif",
    fallbackGradient: "from-amber-600 to-yellow-800",
    alt: "Leonardo DiCaprio Gatsby Toast GIF",
  },
  {
    id: "pedro-pascal-laughing",
    name: "Pedro Laughing to Crying",
    category: "crying",
    emoji: "🎭",
    tag: "PEDRO",
    url: "/memes/pedro-pascal-laughing.gif",
    fallbackGradient: "from-stone-700 to-neutral-900",
    alt: "Pedro Pascal Laughing Then Crying Meme GIF",
  },
  {
    id: "homelander-blank-stare",
    name: "Homelander Stare",
    category: "reaction",
    emoji: "😐",
    tag: "HOMELANDER",
    url: "/memes/homelander-blank-stare.gif",
    fallbackGradient: "from-blue-900 to-red-950",
    alt: "Homelander Blank Stare Movie Theater GIF",
  },
  {
    id: "walter-white-falling",
    name: "Walter White Collapse",
    category: "crying",
    emoji: "🏜️",
    tag: "WALTER",
    url: "/memes/walter-white-falling.gif",
    fallbackGradient: "from-amber-800 to-stone-900",
    alt: "Walter White Falling In Desert Breaking Bad GIF",
  },
  {
    id: "undertaker-behind-meme",
    name: "Right Behind You",
    category: "reaction",
    emoji: "⚰️",
    tag: "UNDERTAKER",
    url: "/memes/undertaker-behind-meme.gif",
    fallbackGradient: "from-purple-950 to-slate-950",
    alt: "Undertaker Standing Behind AJ Styles GIF",
  },
  {
    id: "galaxy-brain-ascended",
    name: "Galaxy Brain (500 IQ)",
    category: "funny",
    emoji: "🧠",
    tag: "500 IQ",
    url: "/memes/galaxy-brain-ascended.gif",
    fallbackGradient: "from-fuchsia-600 to-cyan-700",
    alt: "Galaxy Brain Ascended Cosmic IQ GIF",
  },
  {
    id: "this-is-fine-fire",
    name: "This Is Fine 🔥",
    category: "funny",
    emoji: "☕",
    tag: "THIS IS FINE",
    url: "/memes/this-is-fine-fire.gif",
    fallbackGradient: "from-orange-600 to-red-800",
    alt: "This Is Fine Dog In Fire GIF",
  },
  {
    id: "dr-livesey-walk",
    name: "Dr. Livesey Phonk Walk",
    category: "hype",
    emoji: "🚶",
    tag: "PHONK WALK",
    url: "/memes/dr-livesey-walk.gif",
    fallbackGradient: "from-indigo-700 to-purple-950",
    alt: "Dr Livesey Chad Walk Phonk Meme GIF",
  },
  {
    id: "heart-eyes",
    name: "Down Bad / In Love",
    category: "cute",
    emoji: "💖",
    tag: "LOVE",
    url: "/memes/heart-eyes.gif",
    fallbackGradient: "from-rose-500 to-pink-600",
    alt: "Heart Eyes Anime Meme GIF",
  },
  {
    id: "thumbs-up-cat",
    name: "Thumbs Up Cat 👍",
    category: "cute",
    emoji: "👍",
    tag: "GOOD",
    url: "/memes/thumbs-up-cat.gif",
    fallbackGradient: "from-amber-500 to-emerald-600",
    alt: "Thumbs Up Cat Good Job GIF",
  },
];

export const MEME_CATEGORIES = [
  { id: "all", label: "All Memes" },
  { id: "hype", label: "🔥 Hype & Peak" },
  { id: "reaction", label: "👀 Reaction & Twists" },
  { id: "crying", label: "😭 Pain & Cliffhanger" },
  { id: "funny", label: "😂 Funny & Troll" },
  { id: "cute", label: "✨ Chibi & Cute" },
] as const;

// Top reaction memes displayed directly below the chapter
export const CHAPTER_BOTTOM_REACTION_MEMES = [
  { id: "peak-fiction", emoji: "🗿", label: "Peak Fiction", desc: "Pure cinema" },
  { id: "absolute-cinema", emoji: "🍿", label: "Absolute Cinema", desc: "10/10 masterpiece" },
  { id: "nah-id-win", emoji: "🔥", label: "Nah, I'd Win", desc: "Hype overload" },
  { id: "pure-aura", emoji: "⚡", label: "Pure Aura", desc: "+10,000 aura" },
  { id: "plot-twist-mindblown", emoji: "🤯", label: "Plot Twist!", desc: "Did NOT see that coming" },
  { id: "cliffhanger-pain", emoji: "😫", label: "Need Next Ch!", desc: "The cliffhanger is cruel" },
  { id: "emotional-damage", emoji: "😭", label: "Emotional Damage", desc: "Right in the feels" },
  { id: "fraud-watch", emoji: "🤡", label: "Fraud Watch", desc: "Bro got exposed" },
] as const;
