export interface MemeSticker {
  id: string;
  name: string;
  category: "hype" | "funny" | "reaction" | "crying" | "cute" | "hype_moments" | "all";
  emoji: string;
  tag: string;
  url: string;
  fallbackGradient?: string;
  alt: string;
}

export const POPULAR_MEME_STICKERS: MemeSticker[] = [
  // ── HYPE & PEAK MOMENTS ─────────────────────────────────────
  {
    id: "peak-fiction",
    name: "Peak Fiction",
    category: "hype",
    emoji: "🗿",
    tag: "PEAK",
    url: "/memes/peak-fiction.svg",
    fallbackGradient: "from-amber-600 to-orange-700",
    alt: "Peak Fiction Meme Sticker",
  },
  {
    id: "absolute-cinema",
    name: "Absolute Cinema",
    category: "hype",
    emoji: "🍿",
    tag: "CINEMA",
    url: "/memes/absolute-cinema.svg",
    fallbackGradient: "from-purple-600 to-indigo-800",
    alt: "Absolute Cinema Meme Sticker",
  },
  {
    id: "nah-id-win",
    name: "Nah, I'd Win",
    category: "hype",
    emoji: "🔥",
    tag: "GOJO",
    url: "/memes/nah-id-win.svg",
    fallbackGradient: "from-blue-600 to-cyan-600",
    alt: "Nah I'd Win Gojo Meme Sticker",
  },
  {
    id: "pure-aura",
    name: "Pure Aura (+10,000)",
    category: "hype",
    emoji: "⚡",
    tag: "AURA",
    url: "/memes/pure-aura.svg",
    fallbackGradient: "from-yellow-500 to-amber-600",
    alt: "Pure Aura Meme Sticker",
  },
  {
    id: "gigachad",
    name: "Gigachad",
    category: "hype",
    emoji: "👑",
    tag: "CHAD",
    url: "/memes/gigachad.svg",
    fallbackGradient: "from-zinc-700 to-zinc-900",
    alt: "Gigachad Meme Sticker",
  },
  {
    id: "let-him-cook",
    name: "Let Him Cook",
    category: "hype",
    emoji: "🍳",
    tag: "COOKING",
    url: "/memes/let-him-cook.svg",
    fallbackGradient: "from-emerald-600 to-teal-800",
    alt: "Let Him Cook Meme Sticker",
  },
  {
    id: "domain-expansion",
    name: "Domain Expansion",
    category: "hype",
    emoji: "🤞",
    tag: "JJK",
    url: "/memes/domain-expansion.svg",
    fallbackGradient: "from-violet-600 to-purple-900",
    alt: "Domain Expansion Meme Sticker",
  },
  {
    id: "my-goat",
    name: "My GOAT",
    category: "hype",
    emoji: "🐐",
    tag: "GOAT",
    url: "/memes/my-goat.svg",
    fallbackGradient: "from-rose-600 to-pink-800",
    alt: "My GOAT Meme Sticker",
  },

  // ── FUNNY & TROLL ───────────────────────────────────────────
  {
    id: "anya-heh",
    name: "Anya Heh",
    category: "funny",
    emoji: "😏",
    tag: "SMUG",
    url: "/memes/anya-heh.svg",
    fallbackGradient: "from-pink-500 to-rose-600",
    alt: "Anya Smug Heh Meme Sticker",
  },
  {
    id: "fraud-watch",
    name: "Fraud Watch",
    category: "funny",
    emoji: "🤡",
    tag: "FRAUD",
    url: "/memes/fraud-watch.svg",
    fallbackGradient: "from-red-600 to-orange-700",
    alt: "Fraud Watch Clown Meme Sticker",
  },
  {
    id: "saitama-ok",
    name: "Saitama OK",
    category: "funny",
    emoji: "🥊",
    tag: "OK",
    url: "/memes/saitama-ok.svg",
    fallbackGradient: "from-yellow-600 to-red-600",
    alt: "Saitama OK Meme Sticker",
  },
  {
    id: "skull-dead",
    name: "I'm Dead 💀",
    category: "funny",
    emoji: "💀",
    tag: "DEAD",
    url: "/memes/skull-dead.svg",
    fallbackGradient: "from-zinc-800 to-black",
    alt: "Skull Dead Laughing Meme Sticker",
  },
  {
    id: "popcorn-drama",
    name: "Here for Drama",
    category: "funny",
    emoji: "🍿",
    tag: "DRAMA",
    url: "/memes/popcorn-drama.svg",
    fallbackGradient: "from-amber-500 to-yellow-600",
    alt: "Popcorn Drama Meme Sticker",
  },
  {
    id: "stonks-up",
    name: "Manga Stocks 📈",
    category: "funny",
    emoji: "📈",
    tag: "STONKS",
    url: "/memes/stonks-up.svg",
    fallbackGradient: "from-emerald-600 to-green-700",
    alt: "Stonks Rising Meme Sticker",
  },
  {
    id: "cat-dance",
    name: "Vibing / Happy",
    category: "funny",
    emoji: "💃",
    tag: "VIBE",
    url: "/memes/cat-dance.svg",
    fallbackGradient: "from-pink-600 to-purple-600",
    alt: "Cat Vibing Meme Sticker",
  },

  // ── CHAPTER REACTIONS & TWISTS ───────────────────────────────
  {
    id: "shocked-enel",
    name: "Shocked Face",
    category: "reaction",
    emoji: "😱",
    tag: "SHOCK",
    url: "/memes/shocked-enel.svg",
    fallbackGradient: "from-blue-500 to-indigo-700",
    alt: "Shocked Face Meme Sticker",
  },
  {
    id: "plot-twist-mindblown",
    name: "Plot Twist!",
    category: "reaction",
    emoji: "🤯",
    tag: "TWIST",
    url: "/memes/plot-twist-mindblown.svg",
    fallbackGradient: "from-indigo-600 to-violet-800",
    alt: "Plot Twist Mind Blown Meme Sticker",
  },
  {
    id: "he-just-like-me",
    name: "Literally Me Fr",
    category: "reaction",
    emoji: "🕶️",
    tag: "LITERAL ME",
    url: "/memes/he-just-like-me.svg",
    fallbackGradient: "from-slate-700 to-slate-900",
    alt: "Literally Me Meme Sticker",
  },
  {
    id: "sipping-tea",
    name: "Sipping Tea ☕",
    category: "reaction",
    emoji: "☕",
    tag: "CHILL",
    url: "/memes/sipping-tea.svg",
    fallbackGradient: "from-amber-700 to-stone-800",
    alt: "Sipping Tea Meme Sticker",
  },
  {
    id: "sus-glance",
    name: "Wait... Sus 🤨",
    category: "reaction",
    emoji: "🤨",
    tag: "SUS",
    url: "/memes/sus-glance.svg",
    fallbackGradient: "from-orange-600 to-stone-900",
    alt: "Wait Sus Meme Sticker",
  },
  {
    id: "bro-ran-away",
    name: "NIGERUNDAYO!",
    category: "reaction",
    emoji: "🏃",
    tag: "RUN",
    url: "/memes/bro-ran-away.svg",
    fallbackGradient: "from-amber-600 to-red-700",
    alt: "Nigerundayo Meme Sticker",
  },

  // ── CRYING & EMOTIONAL DAMAGE ───────────────────────────────
  {
    id: "cliffhanger-pain",
    name: "Need Next Ch!",
    category: "crying",
    emoji: "😫",
    tag: "NEED NEXT CH",
    url: "/memes/cliffhanger-pain.svg",
    fallbackGradient: "from-blue-700 to-slate-900",
    alt: "Need Next Chapter Meme Sticker",
  },
  {
    id: "emotional-damage",
    name: "Emotional Damage",
    category: "crying",
    emoji: "😭",
    tag: "PAIN",
    url: "/memes/emotional-damage.svg",
    fallbackGradient: "from-rose-700 to-red-900",
    alt: "Emotional Damage Meme Sticker",
  },
  {
    id: "aqua-crying",
    name: "Aqua Crying",
    category: "crying",
    emoji: "😭",
    tag: "SOB",
    url: "/memes/aqua-crying.svg",
    fallbackGradient: "from-cyan-600 to-blue-800",
    alt: "Aqua Crying Meme Sticker",
  },
  {
    id: "guts-pain",
    name: "Guts Theme / Suffering",
    category: "crying",
    emoji: "⚔️",
    tag: "GUTS",
    url: "/memes/guts-pain.svg",
    fallbackGradient: "from-zinc-800 to-neutral-950",
    alt: "Guts Suffering Meme Sticker",
  },
  {
    id: "salute-respect",
    name: "Respect / Salute",
    category: "crying",
    emoji: "🫡",
    tag: "SALUTE",
    url: "/memes/salute-respect.svg",
    fallbackGradient: "from-emerald-700 to-slate-900",
    alt: "Respect Salute Meme Sticker",
  },

  // ── CHIBI & WHOLESOME ───────────────────────────────────────
  {
    id: "anya-waku-waku",
    name: "Waku Waku ✨",
    category: "cute",
    emoji: "✨",
    tag: "EXCITED",
    url: "/memes/anya-waku-waku.svg",
    fallbackGradient: "from-pink-500 to-purple-600",
    alt: "Waku Waku Meme Sticker",
  },
  {
    id: "heart-eyes",
    name: "Down Bad / In Love",
    category: "cute",
    emoji: "💖",
    tag: "LOVE",
    url: "/memes/heart-eyes.svg",
    fallbackGradient: "from-rose-500 to-pink-600",
    alt: "Down Bad Love Meme Sticker",
  },
  {
    id: "thumbs-up-cat",
    name: "Thumbs Up Cat 👍",
    category: "cute",
    emoji: "👍",
    tag: "GOOD",
    url: "/memes/thumbs-up-cat.svg",
    fallbackGradient: "from-amber-500 to-emerald-600",
    alt: "Thumbs Up Cat Meme Sticker",
  },
];

export const MEME_CATEGORIES = [
  { id: "all", label: "All Memes" },
  { id: "hype", label: "🔥 Hype & Peak" },
  { id: "reaction", label: "👀 Reaction & Twists" },
  { id: "crying", label: "😭 Pain & Cliffhanger" },
  { id: "funny", label: "😂 Funny & Troll" },
  { id: "cute", label: "✨ Chibi & Cute" },
] as const;

// Top reaction memes displayed directly below the chapter
export const CHAPTER_BOTTOM_REACTION_MEMES = [
  { id: "peak-fiction", emoji: "🗿", label: "Peak Fiction", desc: "Pure cinema" },
  { id: "absolute-cinema", emoji: "🍿", label: "Absolute Cinema", desc: "10/10 masterpiece" },
  { id: "nah-id-win", emoji: "🔥", label: "Nah, I'd Win", desc: "Hype overload" },
  { id: "pure-aura", emoji: "⚡", label: "Pure Aura", desc: "+10,000 aura" },
  { id: "plot-twist-mindblown", emoji: "🤯", label: "Plot Twist!", desc: "Did NOT see that coming" },
  { id: "cliffhanger-pain", emoji: "😫", label: "Need Next Ch!", desc: "The cliffhanger is cruel" },
  { id: "emotional-damage", emoji: "😭", label: "Emotional Damage", desc: "Right in the feels" },
  { id: "fraud-watch", emoji: "🤡", label: "Fraud Watch", desc: "Bro got exposed" },
] as const;
